import sqlite3
conn = sqlite3.connect("afternoon db")
print("Opened database successfully")
conn.execute("INSERT INTO EMPLOYEES VALUES (1,'Dennis Kuria',34,57000.00)")
conn.execute("INSERT INTO EMPLOYEES VALUES (2,'Cole Bennet',39,75000.00)")
conn.execute("INSERT INTO EMPLOYEES VALUES (3,'Victor Kamau',35,63000.00)")
conn.execute("INSERT INTO EMPLOYEES VALUES (4,'Veronica Smith',32,65000.00)")
conn.commit()
print("Employee inserted successfully")
conn.close()